"""Rust-backed card filter engine (PyO3 extension)."""

from .card_engine import QueryEngine as QueryEngine

# Columns fetched from magic.cards to populate the engine store.
# Must match what card_from_pydict() reads in src/lib.rs.
ENGINE_COLUMNS: list[str] = [
    "scryfall_id",
    "oracle_id",
    "illustration_id",
    "card_artist",
    "card_border",
    "card_color_identity",
    "card_colors",
    "card_frame_data",
    "card_is_tags",
    "card_keywords",
    "card_layout",
    "card_legalities",
    "card_name",
    "card_oracle_tags",
    "card_rarity_int",
    "card_set_code",
    "card_subtypes",
    "card_types",
    "card_watermark",
    "cmc",
    "collector_number",
    "collector_number_int",
    "creature_power",
    "creature_toughness",
    "edhrec_rank",
    "flavor_text",
    "mana_cost_jsonb",
    "mana_cost_text",
    "oracle_text",
    "planeswalker_loyalty",
    "price_eur",
    "price_tix",
    "price_usd",
    "produced_mana",
    "released_at",
    "creature_power_text",
    "creature_toughness_text",
    "set_name",
    "type_line",
    "prefer_score",
    "cubecobra_score",
]
